#!/usr/bin/env bash
# Regenerate pkg/mzml/testdata/psi_ms_terms.tsv from the authoritative PSI-MS
# ontology, then verify that every accession/name pair the writer can emit still
# exists upstream with exactly that name.
#
# The snapshot is committed so `go test ./...` stays hermetic; run this script
# when adding CV terms or refreshing the ontology pin, and update
# mzml.DefaultMSVersion to the printed data-version.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/pkg/mzml/testdata/psi_ms_terms.tsv"
CV="${REPO_ROOT}/pkg/mzml/cv.go"
SRC_URL="https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if [[ -n "${PSI_MS_OBO:-}" ]]; then
  cp "$PSI_MS_OBO" "$TMP"
else
  command -v curl >/dev/null || { echo "curl is required" >&2; exit 1; }
  curl -sSL --max-time 300 -o "$TMP" "$SRC_URL"
fi

PY="${PYTHON:-python3}"
command -v "$PY" >/dev/null || { echo "python3 is required" >&2; exit 1; }

"$PY" - "$TMP" "$CV" "$OUT" <<'PYEOF'
import re
import sys

obo_path, cv_path, out_path = sys.argv[1:4]
with open(obo_path, encoding="utf-8", errors="replace") as fh:
    obo = fh.read()

byid = {}
for block in obo.split("[Term]")[1:]:
    tid = re.search(r"^id: (\S+)", block, re.M)
    nm = re.search(r"^name: (.*)$", block, re.M)
    obs = bool(re.search(r"^obsolete: true", block, re.M))
    if tid and nm:
        byid[tid.group(1)] = (nm.group(1).strip(), obs)

m = re.search(r"^data-version: (.*)$", obo, re.M)
version = m.group(1).strip() if m else "unknown"

with open(cv_path, encoding="utf-8") as fh:
    go = fh.read()

# accession/name pairs exactly as the writer emits them
pairs = re.findall(r'CVTerm\{\s*"((?:MS|UO):\d{7})"\s*,\s*"([^"]+)"', go)
accs = set(re.findall(r'"((?:MS|UO):\d{7})"', go))

missing, mismatched, rows = [], [], []
for acc in sorted(accs):
    if acc not in byid:
        missing.append(acc)
        continue
    name, obs = byid[acc]
    rows.append((acc, name, "obsolete" if obs else ""))

for acc, emitted in pairs:
    if acc in byid and byid[acc][0] != emitted:
        mismatched.append((acc, emitted, byid[acc][0]))

with open(out_path, "w", encoding="utf-8") as fh:
    fh.write("# PSI-MS ontology snapshot: data-version %s\n" % version)
    fh.write("# Generated by scripts/fetch_psi_ms_cv.sh; columns: accession, name, obsolete\n")
    for acc, name, obs in rows:
        fh.write("%s\t%s\t%s\n" % (acc, name, obs))

print("snapshot: %d terms, data-version %s" % (len(rows), version))
if missing:
    print("MISSING FROM ONTOLOGY: %s" % ", ".join(missing))
if mismatched:
    print("NAME MISMATCHES (emitted vs ontology):")
    for acc, emitted, actual in mismatched:
        print("  %s: emitted %r ontology %r" % (acc, emitted, actual))
if missing or mismatched:
    sys.exit(1)
PYEOF

echo "OK: snapshot written to $OUT"
echo "Set mzml.DefaultMSVersion if the printed data-version changed."
